version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: emprendeia_postgres
    environment:
      POSTGRES_DB: emprendeia_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - emprendeia-net

  ms-ia:
    build: 
      context: ../emprede-ia-microservice/ms-ia  # <-- Ajusta esta ruta a donde esté la carpeta de la IA
    container_name: emprendeia_ms_ia
    ports:
      - "8000:8000"
    environment:
      - LLM_PROVIDER=gemini 
      - LLM_MODEL=gemini-3-flash-preview
      - LLM_API_KEY=
      - CONTEXT_SERVICE_BASE_URL=http://host.docker.internal:5246
      - CONTEXT_SERVICE_API_KEY=SUPER_INTERNAL_API_KEY
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - emprendeia-net

networks:
  emprendeia-net:
    driver: bridge

volumes:
  postgres_data: